[tools]
# Runtimes
go = "latest"
java = "21"
node = "22"
rust = "nightly"

# LSP
"aqua:LuaLS/lua-language-server" = "latest"
"ubi:clangd/clangd" = "latest"
"npm:vscode-langservers-extracted" = "latest" # html, css, json, eslint
"npm:@astrojs/language-server" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:yaml-language-server" = "latest"
"npm:vim-language-server" = "latest"
"npm:@vtsls/language-server" = "latest"
"go:golang.org/x/tools/gopls" = "latest"

# Formatters & linters
"npm:@fsouza/prettierd" = "latest"
"npm:eslint_d" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:github.com/golangci/golangci-lint/cmd/golangci-lint" = "latest"
"go:github.com/cweill/gotests/gotests" = "latest"
"cargo:stylua" = "latest"

# Tools
"cargo:eza" = "latest"
"cargo:tree-sitter-cli" = "latest"
"go:github.com/MSmaili/muxie" = "latest"
